# Use an official Node.js runtime as the base image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy package.json and yarn.lock to the container
COPY package.json yarn.lock ./

# Install dependencies using Yarn
RUN yarn install

# Copy the source code into the container
COPY . .

# Expose the port that the application will run on
EXPOSE 3000

# Define the command to run your application
CMD ["yarn", "start-data-pull"]
